### ISSUE TITLE
getIdByKey is deprecated

### ISSUE THREAD

**Issue by Crabcyborg** [Strategy11/formidable-locations#7]
> PHP Deprecated:  getIdByKey is <strong>deprecated</strong> since version 2.03.05! Use FrmForm::get_id_by_key instead.

Happens multiple times during import.

**Comment by stephywells** [comment]
This has been removed in FF core...

**Comment by Crabcyborg** [comment]
@stephywells it's also used in the API add on. I was going to ask about this in check in tomorrow. I think we may want to put this function back for now.

**Comment by stephywells** [comment]
I'm good with that. I listed two other functions here that we might want to add back also:
https://github.com/Strategy11/formidable-api/issues/136
